<?php

/**
 * @file
 * Functions to support extra fields.
 */

/**
 * Implements hook_theme().
 */
function dnyc_extra_field_theme($existing, $type, $theme, $path) {
  return [
    'dnyc_event_details' => [
      'template' => 'dnyc-event-details',
      'variables' => [
        'start_date' => NULL,
        'end_date' => NULL,
        'location' => NULL,
        'description' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for smart_date_recurring_formatter.
 */
function dnyc_extra_field_preprocess_smart_date_recurring_formatter(&$variables) {
  if (isset($variables['next_display']['#children'])) {
    $link = $variables['next_display']['#children']['link'] ?? NULL;
    unset($variables['next_display']['#children']['link']);
    $content = $variables['next_display']['#children']['date_content'] ?? NULL;
    unset($variables['next_display']['#children']['date_content']);
    $date = $variables['next_display']['#children'];
    // Restructure the content.
    $structured = [
      'date' => $date + [
        '#type' => 'container',
      ],
      'link' => $link,
      'date_content' => $content,
    ];
    $variables['next_display']['#children'] = $structured;
  }
}
