name: drupalnyc
recipe: pantheon
config:
  framework: drupal8
  site: drupalnyc
  id: 948cdd82-38e2-4769-a8fb-d3e33ee4e161
  xdebug: false
  index: false
  edge: true
  cache: false
services:
  appserver:
    build:
      - "cp -n /app/web/sites/example-lando.settings.local.php /app/web/sites/default/settings.local.php"
      - "composer install"
      - "drush cr"
  node:
    type: node:10
    build:
      - "cd /app/web/themes/custom/drupalnyc && npm install"
      - "cd /app/web/themes/custom/drupalnyc && gulp"
    globals:
      gulp-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
