module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  auto_entitylabel: 0
  automated_cron: 0
  background_image: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  config: 0
  config_filter: 0
  config_split: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dcnyc_pantheon: 0
  dnyc_header_block: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_embed: 0
  field: 0
  field_formatter: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  search: 0
  settings_tray: 0
  shortcut: 0
  smart_trim: 0
  system: 0
  taxonomy: 0
  text: 0
  textarea_widget_for_text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  bones: 0
  drupalnyc: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
