bones_fixed_header: 1
bones_search_box: 0
bones_mobile_menu: 1
_core:
  default_config_hash: bK2kTyi6vKRVvk9i3x9l4mGs5HVipWWVyNO6cQVLBi8
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: themes/custom/drupalnyc/logo.svg
favicon:
  use_default: true
