_core:
  default_config_hash: iZmb_hfTgr5OB4nqWbwX70m81Te6yW6H-zMOeEn-ZlU
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  use_default: true
display_back_to_top: false
