bones_fixed_header: 0
bones_search_box: 0
bones_mobile_menu: 1
_core:
  default_config_hash: bK2kTyi6vKRVvk9i3x9l4mGs5HVipWWVyNO6cQVLBi8
features:
  node_user_picture: false
  comment_user_picture: false
  comment_user_verification: false
  favicon: true
logo:
  use_default: true
favicon:
  use_default: true
