_core:
  default_config_hash: t4OwyWVov2EL0wVuIRk03eEbtwz13Mm2F52bSv1KSSs
paragraphs_library:
  - ContactPoint
  - MedicalAudience
  - MedicalContraindication
  - MedicalIndication
  - MedicalCause
  - MedicalProcedure
  - MedicalRiskFactor
  - MedicalTherapy
  - MedicalSignOrSymptom
  - Statement
  - Quotation
  - CollectionPage
  - ItemList
  - MediaGallery
  - ImageGallery
  - VideoGallery
  - WebContent
