_core:
  default_config_hash: pfwJlUBk3sbOWyx51OAnCs4WSYQSE4T9CZ9se25t2mc
default_types:
  - WebPage
  - Article
  - Organization
  - Event
default_paragraph_types: {  }
default_paragraph_layouts:
  layout:
    - layout_onecol
    - layout_twocol_section
    - layout_twocol
    - layout_twocol_bricks
    - layout_threecol_section
    - layout_threecol_25_50_25
    - layout_threecol_33_34_33
    - layout_fourcol_section
default_view_display_components:
  - links
  - mainEntity
