_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: c900923a-2fdb-479b-917e-04a0c6e8cfc7
name: DrupalNYC
mail: domains@drupalnyc.org
slogan: ''
page:
  403: ''
  404: ''
  front: /node/31
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
