<?php

/**
 * @file
 * Functions to support style options.
 */

use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_preprocess_HOOK().
 */
function drupalnyc_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['elements']['#paragraph'];
  if ($paragraph instanceof Paragraph && $paragraph->bundle() === 'hero') {
    $variables['media_position'] = $paragraph->getBehaviorSetting(
      'style_options',
      ['media_position', 'media_position'],
      'overlay',
    );
  }
}
